[project]
name = "memory-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <4.0"
dependencies = [
    "arkitect",
]

[tool.uv.sources]
arkitect = { workspace = true }
